### ISSUE TITLE
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void com.karumi.dexter.DexterInstance.onActivityReady(android.app.Activity)' on a null object reference

### ISSUE THREAD

**Issue by cioraneanu** [Karumi/Dexter#107] opened 2017-01-16 13:23 UTC
### Expected behaviour
To work without crashing.

### Actual behaviour
Received crash reports from several users with the folosing stacktrace:
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{MYPACKAGE/com.karumi.dexter.DexterActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.karumi.dexter.DexterInstance.onActivityReady(android.app.Activity)' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3254)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350)
       at android.app.ActivityThread.access$1100(ActivityThread.java:222)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7237)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void com.karumi.dexter.DexterInstance.onActivityReady(android.app.Activity)' on a null object reference
       at com.karumi.dexter.Dexter.onActivityReady(Dexter.java:138)
       at com.karumi.dexter.DexterActivity.onCreate(DexterActivity.java:31)
       at android.app.Activity.performCreate(Activity.java:6876)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3207)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350)
       at android.app.ActivityThread.access$1100(ActivityThread.java:222)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7237)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

### Steps to reproduce
I didn't have any crashes on my device but this is how the library is used. In an Activity:

```
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        setContentView(R.layout.activity_login);
        PermissionListener dialogPermissionListener =
                DialogOnDeniedPermissionListener.Builder
                        .withContext(this)
                        .withTitle("Title")
                        .withMessage("Message")
                        .withButtonText(android.R.string.ok)
                        .withIcon(R.mipmap.ic_launcher)
                        .build();
        Dexter.withActivity(this)
                .withPermission(Manifest.permission.GET_ACCOUNTS)
                .withListener(dialogPermissionListener).check();
}
```

### Version of the library
3.0.0

**Comment by rfgamaral** [comment] 2017-01-23 16:33
I'm having the same issue...

**Comment by MagicDroidX** [comment] 2017-01-28 14:14
Same here :/

**Comment by pedrovgs** [comment] 2017-01-30 13:40
@Serchinastico could this be related to the issue we've already fixed? #105

**Comment by xoex** [comment] 2017-01-30 14:06
same here

>                                                                       java.lang.RuntimeException: Unable to start activity ComponentInfo{ir.dolphinapp.root.emu/com.karumi.dexter.DexterActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.karumi.dexter.DexterInstance.onActivityReady(android.app.Activity)' on a null object reference
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                          at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:148)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                       Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.karumi.dexter.DexterInstance.onActivityReady(android.app.Activity)' on a null object reference
                                                                          at com.karumi.dexter.Dexter.onActivityReady(Dexter.java:140)
                                                                          at com.karumi.dexter.DexterActivity.onCreate(DexterActivity.java:31)
                                                                          at android.app.Activity.performCreate(Activity.java:6237)
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                          at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:148) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                          at java.lang.reflect.Method.invoke(Native Method)

**Comment by xoex** [comment] 2017-01-30 14:12
this was happened, when i was changing permission from App (from settings), then I switched to my app and then it crashed.

**Comment by pedrovgs** [comment] 2017-01-30 14:21
@xoex, @MagicDroidX or @rfgamaral could you try with the version ``3.0.1`` we released last week? I think this issue could be related. If anyone could paste here some steps to reproduce that could really help :)

**Comment by xoex** [comment] 2017-01-30 14:42
@pedrovgs Mine was `3.0.1`  , but I don't know how to reproduce it

**Comment by pedrovgs** [comment] 2017-01-30 15:09
@xoex how many crashes did you have?

**Comment by xoex** [comment] 2017-01-30 15:16
@pedrovgs I am developing the app, so I can't check clients. It happened in my second or third use, when I was switching from Settings (trying to change permissions) to my activity. 
I tried to the same routine but it didn't happened again.

**Comment by rfgamaral** [comment] 2017-01-30 17:48
I personally can't reproduce this myself, I only get the crash reports on Crashlytics. But I'll upgrade Dexter ASAP.

**Comment by MagicDroidX** [comment] 2017-01-31 03:55
IMO, this may happen when the activity is somehow recycled.

**Comment by xoex** [comment] 2017-01-31 07:20
Why not put some null checking to prevent crash?

**Comment by Serchinastico** [comment] 2017-01-31 08:10
We will deal with the issue tomorrow morning, if you feel like you can't wait until tomorrow, please, send us a PR! We will be glad to review it!

**Comment by Serchinastico** [comment] 2017-02-01 14:20
Good news everyone, we are releasing Dexter 3.0.2 that solves the issue and will be ready to use in a couple hours.

We've been able to reproduce the bug by going to the settings, rejecting manually some permissions and going back to the app. We just introduced a null check because in that scenario the library doesn't know how to deal with that situation (no Dexter `instance` created).

I'll be closing this issue for now, let us know if you still have the same problem and we will review it again.
Thank you all for the reports and your patience!

**Closed by Serchinastico** 2017-02-01 14:20 UTC
Labels: bug

**Comment by rfgamaral** [comment] 2017-02-01 16:43
Awesome. Going to update now and close the issue on our side. Thanks for handling this quickly :)

**Comment by ganfra** [comment] 2017-11-17 16:08
Hi @rfgamaral 
Seems like the issue is back on version 4.1.0...
I can't reproduce, but I have some crash related to this in Crashlytics

```
Fatal Exception: java.lang.RuntimeException: Unable to destroy activity {com.transdevidf.android.recfonc/com.karumi.dexter.DexterActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.karumi.dexter.e.a()' on a null object reference
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4634)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4661)
       at android.app.ActivityThread.-wrap7(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1703)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void com.karumi.dexter.e.a()' on a null object reference
       at com.karumi.dexter.Dexter.onActivityReady(Unknown Source)
       at com.karumi.dexter.DexterActivity.onDestroy(Unknown Source)
       at android.app.Activity.performDestroy(Activity.java:7208)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1161)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4621)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4661)
       at android.app.ActivityThread.-wrap7(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1703)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
```

Thanks :-)

**Comment by MohNage7** [comment] 2017-12-09 10:20
@ganfra  yeah it happens with me too at 4.1.0

**Comment by nick252** [comment] 2017-12-27 10:00
same crash on Dexter 4.2

com.karumi.dexter.DexterActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.finish()' on a null object reference
       at android.app.ActivityThread.deliverResults(ActivityThread.java:3919)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:3962)
       at android.app.ActivityThread.access$1500(ActivityThread.java:180)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1543)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5791)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.finish()' on a null object reference
       at com.karumi.dexter.DexterInstance.onPermissionsChecked(Unknown Source)
       at com.karumi.dexter.DexterInstance.updatePermissionsAsGranted(Unknown Source)
       at com.karumi.dexter.DexterInstance.onPermissionRequestGranted(Unknown Source)
       at com.karumi.dexter.Dexter.onPermissionsRequested(Unknown Source)
       at com.karumi.dexter.DexterActivity.onRequestPermissionsResult(Unknown Source)
       at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:6604)
       at android.app.Activity.dispatchActivityResult(Activity.java:6483)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:3915)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:3962)
       at android.app.ActivityThread.access$1500(ActivityThread.java:180)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1543)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5791)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
