### ISSUE TITLE
Getting below exception when permission is denied second time in fragment

### ISSUE THREAD

**Issue by rohit6027** [Karumi/Dexter#244] opened 2019-10-30 06:01 UTC
```
 java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=42, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS launchParam=MultiScreenLaunchParams { mDisplayId=0 mFlags=0 } (has extras) }} to activity {com.shopfeur.user/com.karumi.dexter.DexterActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.finish()' on a null object reference
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4472)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4515)
        at android.app.ActivityThread.-wrap22(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1687)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.finish()' on a null object reference
        at com.karumi.dexter.DexterInstance.onPermissionsChecked(Unknown Source)
        at com.karumi.dexter.DexterInstance.updatePermissionsAsDenied(Unknown Source)
        at com.karumi.dexter.DexterInstance.onPermissionRequestDenied(Unknown Source)
        at com.karumi.dexter.Dexter.onPermissionsRequested(Unknown Source)
        at com.karumi.dexter.DexterActivity.onRequestPermissionsResult(Unknown Source)
        at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7434)
        at android.app.Activity.dispatchActivityResult(Activity.java:7260)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4468)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4515) 
        at android.app.ActivityThread.-wrap22(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1687) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6682) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410) 

```

**Comment by pedrovgs** [comment] 2019-11-08 12:13
Hi @rohit6027 could you please provide more information about the error? What's the version of the library you are using when reproducing the error? Can you paste here the piece of code requesting the permission? Could you please list the steps to reproduce the error?

**Comment by rupinderjeet** [comment] 2019-11-29 06:20
Hi, I received this too a few moments ago. I am using an AppCompatActivity and I call this code when a button is tapped. Exception stack trace is same as above.

I am using Kotlin with MVVM.

Library: 'com.karumi:dexter:6.0.0'
OS: Android Emulator v9.0

```
Dexter.withActivity(this)
                .withPermission(Manifest.permission.READ_EXTERNAL_STORAGE)
                .withListener(object: BasePermissionListener() {
                    override fun onPermissionGranted(response: PermissionGrantedResponse?) {
                        openProfileImageSelector()
                    }

                    override fun onPermissionDenied(response: PermissionDeniedResponse?) {
                        toast(R.string.error_perm_image_pick)
                    }
                })
                .check()
```

Is there any quick solution? I rely heavily on Dexter.

**Comment by pedrovgs** [comment] 2019-11-29 08:49
Hi @rohit6027 and @rupinderjeet I've sent a tentative fix for this error because even with the steps to reproduce you mentioned we are not able to reproduce the crash. I'd need you to try to reproduce this error in a demo project we can test manually and also to check if the new version we are going to publish as soon as https://github.com/Karumi/Dexter/pull/246 is merged fixes your issue. If the PR I've doesn't sent doesn't fix the error, please reopen this issue.

**Comment by rohit6027** [comment] 2019-11-29 09:08
ok I will provide you a demo project for this bug asap.

**Comment by rohit6027** [comment] 2019-12-01 14:43
Hi, @pedrovgs I have created a demo project for this exception. Please check it.

Step to produce Exception:- 
1. Permission dialog will be prompted when app launch
2. deny permission
3. dialog will be prompted again
4. deny it again and app will be crashed.

[](https://github.com/rohit6027/GlideException.git)

**Closed** 2019-12-02 14:24 UTC
Labels: bug

**Comment by pedrovgs** [comment] 2019-12-04 10:51
Thank you so much @rohit6027 your project helped me a lot to confirm the latest Dexter release fixed this issue. Update your app to use Dexter 6.0.1 and you won't ever see this error again.
