### ISSUE TITLE
report.isAnyPermissionPermanentlyDenied is always true

### ISSUE THREAD

**Issue by cesarsicas** [Karumi/Dexter#139] opened 2017-03-27 17:25 UTC
Hi, im trying to achieve the following behaviour:

1 - Dexter checks for multiple permissions. 

2 - When ther user click on Deny,  a Dialog is showed  on onPermissionRationaleShouldBeShown() method and token.continuePermissionRequest() is called. Then the activity is closed

3 - When the user click on Allow, my method startApplication() is called . 

But the problem is, inside method onPermissionsChecked(), the value of report.isAnyPermissionPermanentlyDenied is always **true,** and the value of report.areAllPermissionsGranted is always **false** , regardless of which option the user checks. 

How  can i achieve this ?

### Expected behaviour
Check if the user deny or allow multiple permissions

### Actual behaviour
the value of report.isAnyPermissionPermanentlyDenied is always **true,** and the value of report.areAllPermissionsGranted is always **false** , regardless of which option the user checks. 

### Steps to reproduce
```

Dexter.withActivity(this)
                .withPermissions(
                        Manifest.permission.ACCESS_FINE_LOCATION,
                        Manifest.permission.READ_PHONE_STATE,
                        Manifest.permission.ACCESS_NETWORK_STATE,
                        Manifest.permission.ACCESS_COARSE_LOCATION,
                        Manifest.permission.WRITE_EXTERNAL_STORAGE,
                        Manifest.permission.READ_EXTERNAL_STORAGE,
                        Manifest.permission.MANAGE_DOCUMENTS,
                        Manifest.permission.CAMERA
                ).withListener(object : MultiplePermissionsListener {
            override fun onPermissionsChecked(report: MultiplePermissionsReport) {

                if(report.areAllPermissionsGranted()){ // <<<< always false
                    startApplication()
                }


            }

            override fun onPermissionRationaleShouldBeShown(permissions: List<PermissionRequest>, token: PermissionToken) {/* ... */
                DialogUtils.customErrorDialog(this@SplashscreenActivity,
                        "Essas permissões são necessárias para utilizar o Aplicativo"){ onClick ->
                            if(onClick){
                                token.continuePermissionRequest()
                                finish()
                            }
                        }

                    token.continuePermissionRequest()

            }

        }).check()
```

### Version of the library
com.karumi:dexter:3.0.2

**Comment by Serchinastico** [comment] 2017-03-28 08:38
Hi @JulioCesarSiqueira 

Looks like the problem is with the `MANAGE_DOCUMENTS` permission. As stated in the Android documentation, [this permission is not granted to 3rd party apps but only to the platform document management app](https://developer.android.com/reference/android/Manifest.permission.html#MANAGE_DOCUMENTS). If you need this permission you probably have to include a workaround, this are two good references for the known issue: [SO1](http://stackoverflow.com/questions/19837358/android-kitkat-securityexception-when-trying-to-read-from-mediastore), [SO2](http://stackoverflow.com/questions/22178041/getting-permission-denial-exception).

Let us know if this is actually the problem so that we can close the issue.

Thanks again!

**Comment by JulioCesarSiqueira** [comment] 2017-03-28 18:02
@Serchinastico thank you very much!  

I removed this permission and worked great.

**Closed** 2017-04-25 10:01 UTC
