### ISSUE TITLE
SnackbarOnDeniedPermissionListener.Builder.with requires ViewGroup

### ISSUE THREAD

**Issue by stefan-nsk** [Karumi/Dexter#169] opened 2017-08-01 10:26 UTC
### Expected behaviour

```java
SnackbarOnDeniedPermissionListener.Builder.with(
    findViewById(R.id.some_view), R.string.some_text)
```

### Actual behaviour

```java
SnackbarOnDeniedPermissionListener.Builder.with(
    (ViewGroup) findViewById(R.id.some_view), R.string.some_text)
```

### Steps to reproduce

Try to create `SnackbarOnDeniedPermissionListener` using static method of builder.

### Version of the library

**4.1.0**

**Comment by pedrovgs** [comment] 2017-08-02 16:56
Hi @stefan-nsk I guess this is not a bug xD The snack bar component requires a ``ViewGroup`` instance. I'm closing this issue, sorry. If you want to avoid the downcasting you can use a library like [butterknife](https://github.com/JakeWharton/butterknife) so the casting is performed by the library and if the casting fails your app will crash.

**Comment by pedrovgs** [comment] 2017-08-02 17:02
My bad, the library accepts a view and in ``Snackbar:135`` is going to find the view parent. We could change the code to accept ``View`` instead of ``ViewGroup`` as param. As this is not a major feature we will wait for a collaborator PR 😃 if you don't mind.

**Comment by stefan-nsk** [comment] 2017-08-03 16:01
You are welcome: #171.

**Comment by pedrovgs** [comment] 2017-08-03 16:04
uooo thanks!

**Closed** 2017-08-07 13:08 UTC
Labels: enhancement, help wanted
