### ISSUE TITLE
WRITE_EXTERNAL_STORAGE not working on Oreo

### ISSUE THREAD

**Issue by gcatak** [Karumi/Dexter#215] opened 2018-09-17 15:38 UTC
WRITE_EXTERNAL_STORAGE, this permission is not working on Oreo. I am creating images in a folder but for oreo it is not working when it is working for lower versions. How can I solve?

### Version of the library
5.0.0

It gives this error:

> W/System.err: java.io.FileNotFoundException: /storage/emulated/0/Pictures/xx/yy.jpg (No such file or directory)

**Comment by gcatak** [comment] 2018-09-18 10:56
Could you look this SO question, please?

https://stackoverflow.com/questions/52383849/java-io-filenotfoundexception-no-such-file-or-directory-error/52384223?noredirect=1#comment91713796_52384223

**Comment by Serchinastico** [comment] 2018-10-03 13:08
Hi @gcatak,

This is an open source project so feel free to send us a PR fixing the issue and we will gladly merge it and release a new version.

But first, I recommend you to look to:
* https://stackoverflow.com/questions/48172519/oreo-write-external-storage-permission
* https://stackoverflow.com/questions/49775322/how-to-have-read-write-external-storage-after-targeting-android-o-26-8-0

To see if the problem is in other libraries and not Dexter. I'm closing the issue until the bug is not proven to be in Dexter but feel free to reopen it if you find otherwise.

Thanks for reporting.

**Closed by Serchinastico** 2018-10-03 13:08 UTC
