### ISSUE TITLE
it will call onResume?

### ISSUE THREAD

**Issue by chenwulue** [Karumi/Dexter#84] opened 2016-08-26 10:11 UTC
when I call checkPermission,it will call onResume

### Steps to reproduce
 Dexter.checkPermissions

### Version of the library
`2.3.0`

**Comment by Serchinastico** [comment] 2016-09-01 20:29
Hi @chenwulue 

This issue has been already reported in #47 & #81 and solved in #73, that will be part of the version 3.0.0 of the library.

I'll close the issue, subscribe to the issues I mentioned if you want to know when the issue is finally solved. 

Thanks for reporting!

**Closed by Serchinastico** 2016-09-01 20:29 UTC

**Comment by minhbnt-1512** [comment] 2019-12-23 08:19
This issue wasn't fixed in version 6.0.1. it still call onResume

**Comment by Serchinastico** [comment] 2019-12-23 09:15
It calls `onResume` because a native dialog is presented. We can't do anything about that, it's how Android runtime permissions system works. 

If you are seeing an `onResume` call with no dialog whatsoever, please send us a minimal project reproducing the issue so that we can better debug what's going on.
