### ISSUE TITLE
proguard?

### ISSUE THREAD

**Issue by qinyang1018** [Karumi/Dexter#150] opened 2017-05-18 09:46 UTC
### Expected behaviour

![image](https://cloud.githubusercontent.com/assets/15726024/26196522/cda655de-3bf1-11e7-95fb-475179e145f6.png)
Whether to need to configure the proguard
### Version of the library
com.karumi:dexter:4.0.0

**Comment by Serchinastico** [comment] 2017-05-18 10:00
Hi @qinyang1018,

First of all, thanks for reporting!
I'm reading the source code and this is the offending line where the NPE is happening:

```java
void onActivityDestroyed() {
    isRequestingPermission.set(false);
}
```

I can't see how that line can fail (`isRequestingPermission` is initialized in the constructor and never null'ed)
How are you running Dexter? Have you tried updating to the latest release (`4.1.0`)?

**Comment by qinyang1018** [comment] 2017-05-18 10:18
Thank you for your answer
I will try to 4.1.0 and 
```
void onActivityDestroyed() {
    isRequestingPermission.set(false);
}
```
![image](https://cloud.githubusercontent.com/assets/15726024/26197794/27b71348-3bf6-11e7-9eba-8ef50e5a7151.png)

**Comment by Serchinastico** [comment] 2017-05-22 10:51
We are going to release a new version of Dexter with a proguard configuration so that we don't obfuscate any class in Dexter and we can debug what's happening better.

Thanks for reporting!

**Comment by qinyang1018** [comment] 2017-05-23 01:58
ok  thank you

**Comment by qinyang1018** [comment] 2017-05-23 09:45
ok
i will try wait new version 
thank you

**Comment by pedrovgs** [comment] 2017-06-23 13:28
@flipper83 @Serchinastico I've seen you've merged a PR adding proguard support but not exporting the proguard configuration with the aar generated during the release.

You should enable ``consumerProguardFiles`` param as part of your build configuration.

Here you have an example:

```groovy
defaultConfig {
    ...
    consumerProguardFiles 'proguard-rules.pro'
  }
```

**Comment by EmmettWilson** [comment] 2017-06-28 02:46
The stack trace reported here appears to be a duplicate of https://github.com/Karumi/Dexter/issues/153. I say this because `DexterActivity.onDestroy()` on both 4.0 and 4.1 delegates directly and only to `DexterInstance.onActivityDestroyed()` where the null pointer happened. You can see that this is the first reference to Dexter within the call stack.
![image](https://user-images.githubusercontent.com/16154410/27618366-99e2415e-5b81-11e7-970e-bf5098746692.png)

**Comment by Serchinastico** [comment] 2017-06-28 08:43
Thank you @pedrovgs!

I checked the configuration with the project Demo and didn't really used the generated AAR, I'm including the property just now before doing a release.

Cheers!

**Comment by EmmettWilson** [comment] 2017-06-28 13:37
As far as the original exception. This appears to me to be a duplicate of https://github.com/Karumi/Dexter/issues/153?

**Closed** 2017-06-28 13:40 UTC
