### ISSUE TITLE
Dexter only called once

### ISSUE THREAD

**Issue by Isabellle** [Karumi/Dexter#62] opened 2016-05-19 09:48 UTC
### Expected behaviour
Dexter to ask again for permissions if they are turned off in the app settings after having accepted them

### Actual behaviour
When accepting permissions and afterwards turning them off in the settings; I'm expecting Dexter to be called in the onResume method in my BaseActivity. Since there is already a running instance it is called only once.

### Steps to reproduce
Accept permissions, go to settings, go back to the app and see that the permissions are not requested in the onResume

```
@Override
    protected void onResume() {
        super.onResume();

        if (!Dexter.isRequestOngoing()) {
            Dexter.checkPermissions(new MultiplePermissionsListener() {
                @Override public void onPermissionsChecked(MultiplePermissionsReport report) {/* ... */}
                @Override public void onPermissionRationaleShouldBeShown(List<PermissionRequest> permissions, PermissionToken token) {/* ... */}
            }, android.Manifest.permission.READ_EXTERNAL_STORAGE, android.Manifest.permission.WRITE_EXTERNAL_STORAGE, android.Manifest.permission.ACCESS_FINE_LOCATION, android.Manifest.permission.CAMERA);
        }
     }
```

### Version of the library
`com.karumi:dexter:2.2.2`

**Comment by Serchinastico** [comment] 2016-05-30 10:34
Hi @Isabellle 

I'm wondering if you are actually implementing the `onPermissionRationaleShouldBeShown` callback. When the user denies a permission, either through the dialog or the settings, the Android framework gives the app the opportunity to show a rationale to explain your user why do you need that permission. 

In the case of Dexter, this callback is called with a token parameter. Once the app has informed the user, the app **must** use the token to continue the permission request process. If you don't want to show anything at all, you still need to call `token.continuePermissionRequest()` in order to notify Dexter that you are ready to effectively request the permission(s).

This is explained in the [Dexter documentation](https://github.com/Karumi/Dexter#showing-a-rationale). If the problem still persists let us know and we'll see if there is something we can do.

Sorry for the delay and thanks for giving us your feedback!

**Comment by pedrovgs** [comment] 2016-06-20 18:25
Hi @Isabellle I'd like to know if @Serchinastico's comment was helpful. Can we close this issue or the problem is related with the library implementation?

**Comment by Isabellle** [comment] 2016-06-20 18:28
I switched to an homemade solution. Thanks for your assistance.

**Closed** 2016-06-20 18:28 UTC

**Comment by jonl-percsolutions-com** [comment] 2016-12-13 01:00
I ran into this issue today.  The setup documentation is not very clear and it seems that the helpful "builders" should make this work easier.  Instead you have to setup a "helpful" builder listener and then also setup a listener to take care of this other case, which, imo, doesn't seem to be as helpful as it could be.

**Comment by valterh4ck3r** [comment] 2017-09-27 00:03
What is solution ?
